### ISSUE TITLE
Start/End Time Invalid

### ISSUE THREAD

**Issue by rhbarber98** [server-status-project/server-status#61] opened 2018-10-13 06:53 UTC
I am having an issue adding scheduled maintenance. When I select a start and end time, both on the date I am trying to add the post, and also with dates selected days and weeks in the future, I get two messages that pop in from the right of my display. These errors state that both the start and end times are invalid. I have made sure that the end time is indeed after the start time. I love your project and everything works great except for this little wrinkle. See attached screenshot for the exact error. Thank you for your time in working on this project.
<img width="1677" alt="screen shot 2018-10-13 at 02 50 52" src="https://user-images.githubusercontent.com/4080964/46902401-e659ec00-ce92-11e8-99d1-b334bf866e1d.png">

**Comment by Pryx** [comment] 2018-10-13 14:44
Hi, thank you for reporting that! What version are you using?

**Comment by rhbarber98** [comment] 2018-10-13 19:34
Thank you for the quick reply in resolving this issue. I am using the latest tagged release, 1.0.2

**Comment by Pryx** [comment] 2018-10-13 19:39
Can you try if it is fixed on master? There is a unexpected delay with releasing the 1.1.0 and there is a fix for this on master if I recall correctly

**Comment by rhbarber98** [comment] 2018-10-13 20:34
I downloaded the master branch into a new directory on my web server, but the issue is persisting in the latest code.

**Comment by rhbarber98** [comment] 2018-10-28 18:11
Has there been any update on the status of this bug?

**Comment by Pryx** [comment] 2018-10-31 20:51
Sorry, my life has been a bit too busy :slightly_smiling_face: Sadly I couldn't reproduce the issue on latest master that is at demo.status.sajdl.com so I am not sure what the issue could be

**Comment by rhbarber98** [comment] 2019-03-15 19:57
I have just reproduced the issue on your demo site, so it rules out my server being the issue. It has to be a software bug.
<img width="1680" alt="Screen Shot 2019-03-15 at 3 51 11 PM" src="https://user-images.githubusercontent.com/4080964/54458684-fc6a2200-473a-11e9-96de-7142ee63f3fb.png">

**Comment by yigitkeremoktay** [comment] 2020-08-06 11:58
Found the problem.
At least on my case :) you need to specify end time for it to work.

**Comment by yigitkeremoktay** [comment] 2020-08-17 16:11
@rhbarber98 this issue is both fixed in master and [beta releases](https://github.com/yigitkeremoktay/server-status)

**Comment by yigitkeremoktay** [comment] 2020-08-17 16:11
You may now close this issue

**Closed** 2020-08-24 13:08 UTC
Labels: bug
